name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab6-web

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar aplicación TypeScript y Vite
        run: npm run build

      - name: Verificar construcción completada
        if: success()
        run: echo "Build completado exitosamente."
